#!/usr/bin/env node
// Writes llms-full.txt (#59): the full reference in one plain Markdown file,
// for AI assistants and offline reading. It is assembled from the docs, so
// it can't drift from them:
//
//   README.md, docs/api-design.md, MIGRATION.md and SPEC.md, in that order,
//   with the HTML of the README (header, badges, sponsor button) and every
//   HTML comment left out, and relative links made absolute (GitHub, master).
//
//   pnpm docs:llms           rewrite llms-full.txt
//   pnpm docs:llms --check   fail if llms-full.txt is out of date
//
// Run it after `pnpm readme:bench`, which changes README.md. No dependencies.

import { readFileSync, writeFileSync } from "node:fs";
import { join, posix } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = fileURLToPath(new URL("..", import.meta.url));
const OUTPUT = "llms-full.txt";
const REPOSITORY = "https://github.com/josegoval/nif-dni-nie-cif-validation";
const SOURCES = [
  { file: "README.md", title: "Overview (README.md)" },
  {
    file: "docs/api-design.md",
    title: "API reference and design (docs/api-design.md)",
  },
  { file: "MIGRATION.md", title: "Migrating from v1 (MIGRATION.md)" },
  { file: "SPEC.md", title: "Validation rules and their sources (SPEC.md)" },
];

const HEADER = `# nif-dni-nie-cif-validation: full reference

> The full documentation of the npm package \`nif-dni-nie-cif-validation\` in one file: the README, the API reference, the migration guide from v1 and the validation rules with their official sources. The short version is llms.txt.

This file is generated by \`pnpm docs:llms\` (scripts/llms-full.mjs) from ${SOURCES.map((s) => s.file).join(", ")}. Links point to the repository: ${REPOSITORY}.`;

/** Makes a relative link absolute: a file on GitHub, resolved from `from`. */
function absolute(target, from) {
  if (/^(?:[a-z]+:|#)/i.test(target)) return target;
  const [path, fragment] = target.split("#");
  const resolved = posix.normalize(posix.join(posix.dirname(from), path));
  return `${REPOSITORY}/blob/master/${resolved}${fragment ? `#${fragment}` : ""}`;
}

/**
 * Removes HTML comments (markers of generated sections, test markers).
 * Repeats until nothing changes, so a comment hidden inside another one
 * can't leave a "<!--" behind, and fails if one is still unterminated.
 */
function stripComments(markdown, file) {
  let text = markdown;
  let previous;
  do {
    previous = text;
    text = text.replace(/<!--[\s\S]*?-->\n?/g, "");
  } while (text !== previous);
  if (text.includes("<!--")) {
    throw new Error(`llms-full: unterminated HTML comment in ${file}`);
  }
  return text;
}

/** Cleans one source file: no HTML chrome, no comments, absolute links. */
function clean(markdown, file) {
  const out = stripComments(markdown, file)
    // HTML paragraphs: the README header, its language links and its
    // badges; and the sponsor button as a plain link.
    .replace(/^<p(?: [^>]*)?>[\s\S]*?<\/p>\n/gm, "")
    .replace(
      /^<a href="(https:\/\/www\.buymeacoffee\.com[^"]*)"[^\n]*\n/gm,
      "[Buy Me a Coffee]($1)\n"
    )
    // The install tabs: keep the commands, drop the HTML around them.
    .replace(/^<\/?details>\n/gm, "")
    .replace(/^<summary>(.*)<\/summary>\n/gm, "$1:\n")
    .replace(/\]\(([^)\s]+)\)/g, (_, target) => `](${absolute(target, file)})`);
  return out.replace(/\n{3,}/g, "\n\n").trim();
}

function build() {
  const parts = SOURCES.map(({ file, title }) => {
    const markdown = readFileSync(join(ROOT, file), "utf8");
    return `---\n\nSource: ${title}, ${REPOSITORY}/blob/master/${file}\n\n${clean(markdown, file)}`;
  });
  return `${[HEADER, ...parts].join("\n\n")}\n`;
}

function main() {
  const path = join(ROOT, OUTPUT);
  const next = build();
  let current = null;
  try {
    current = readFileSync(path, "utf8");
  } catch {
    // Not written yet.
  }
  if (process.argv.includes("--check")) {
    if (current !== next) {
      console.error(
        `${OUTPUT} is out of date with its sources. Run \`pnpm docs:llms\` and commit the result.`
      );
      process.exit(1);
    }
    console.log(`${OUTPUT} matches its sources.`);
    return;
  }
  if (current !== next) {
    writeFileSync(path, next);
    console.log(`Updated ${OUTPUT} (${next.length} characters)`);
  }
}

main();
