name: Release
on:
  push:
    branches: [master, next, next-major, beta, alpha]
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "14"
      - name: Install dependencies
        run: yarn install --frozen-lockfile --immutable --ignore-engines
      - name: Run tests
        run: yarn test
      - name: Build package
        run: yarn build
      - name: Setup Node 18
        uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release